apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replica
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: 
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webappcontainer
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queuecontainer
    image: richardchesterwood/k8s-fleetman-queue:release1